import { z } from 'zod';

export const engineerSchema = z.object({
  id: z.string().uuid(),
  email: z.string().email(),
  name: z.string(),
  avatar: z.string().url().optional(),
  role: z.enum(['Engineer', 'Senior Engineer', 'Lead Engineer', 'Manager', 'Director']),
  team: z.string(),
  applications: z.array(z.string()),
  expertise: z.array(z.string()),
  isActive: z.boolean(),
  hireDate: z.coerce.date(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
  preferences: z.object({
    timezone: z.string(),
    notifications: z.object({
      email: z.boolean(),
      slack: z.boolean(),
      inApp: z.boolean(),
    }),
    workingHours: z.object({
      start: z.string().regex(/^([01]\d|2[0-3]):([0-5]\d)$/),
      end: z.string().regex(/^([01]\d|2[0-3]):([0-5]\d)$/),
      days: z.array(z.number().int().min(0).max(6)),
    }),
  }),
});

export const applicationSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  displayName: z.string(),
  description: z.string(),
  owner: z.string(),
  ownerEmail: z.string().email(),
  team: z.string(),
  criticality: z.enum(['Critical', 'High', 'Medium', 'Low']),
  type: z.enum(['Internal', 'Customer-Facing', 'Infrastructure', 'Platform', 'Mobile', 'Web']),
  environment: z.enum(['Production', 'Staging', 'Development', 'Mixed']),
  technologies: z.array(z.string()),
  dependencies: z.array(z.string()),
  slaTargets: z.object({
    responseTime: z.number().int().positive(),
    resolutionTime: z.number().int().positive(),
  }),
  healthThresholds: z.object({
    healthy: z.number().min(0).max(100),
    degraded: z.number().min(0).max(100),
    critical: z.number().min(0).max(100),
  }),
  isActive: z.boolean(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});

export const monthlyReportSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  period: z.object({
    start: z.coerce.date(),
    end: z.coerce.date(),
  }),
  status: z.enum(['draft', 'pending-review', 'approved', 'published', 'archived']),
  generatedBy: z.string(),
  generatedAt: z.coerce.date(),
  reviewedBy: z.string().optional(),
  reviewedAt: z.coerce.date().optional(),
  approvedBy: z.string().optional(),
  approvedAt: z.coerce.date().optional(),
  publishedAt: z.coerce.date().optional(),
  executiveSummary: z.string(),
  kpis: z.array(z.object({
    id: z.string().uuid(),
    name: z.string(),
    value: z.union([z.number(), z.string()]),
    target: z.union([z.number(), z.string()]),
    unit: z.string(),
    status: z.enum(['on-track', 'at-risk', 'off-track']),
    trend: z.number(),
    description: z.string(),
    category: z.enum(['volume', 'performance', 'quality', 'satisfaction', 'risk']),
  })),
  charts: z.array(z.object({
    id: z.string().uuid(),
    type: z.enum(['line', 'bar', 'pie', 'donut', 'area', 'scatter', 'heatmap', 'radar']),
    title: z.string(),
    data: z.unknown(),
    config: z.record(z.unknown()),
    insights: z.array(z.string()),
  })),
  operationalRisks: z.array(z.object({
    id: z.string().uuid(),
    title: z.string(),
    description: z.string(),
    likelihood: z.enum(['Low', 'Medium', 'High']),
    impact: z.enum(['Low', 'Medium', 'High', 'Critical']),
    riskScore: z.number().int().min(1).max(25),
    category: z.enum(['Technical', 'Process', 'Resource', 'Vendor', 'Security', 'Compliance']),
    affectedApplications: z.array(z.string()),
    affectedTeams: z.array(z.string()),
    mitigation: z.string(),
    owner: z.string(),
    status: z.enum(['open', 'mitigating', 'monitored', 'accepted', 'closed']),
    identifiedAt: z.coerce.date(),
    lastReviewedAt: z.coerce.date(),
    nextReviewAt: z.coerce.date(),
  })),
  recurringIssues: z.array(z.object({
    id: z.string().uuid(),
    title: z.string(),
    description: z.string(),
    pattern: z.string(),
    frequency: z.number().int().positive(),
    affectedApplications: z.array(z.string()),
    affectedTickets: z.array(z.string()),
    rootCause: z.string(),
    currentWorkaround: z.string(),
    permanentFix: z.string(),
    fixStatus: z.enum(['not-started', 'in-progress', 'testing', 'deployed', 'verified']),
    fixOwner: z.string(),
    fixTargetDate: z.coerce.date(),
    businessImpact: z.enum(['Low', 'Medium', 'High', 'Critical']),
    slaImpact: z.number().min(0).max(100),
    costEstimate: z.number().nonnegative(),
    aiConfidence: z.number().min(0).max(1),
    identifiedAt: z.coerce.date(),
    lastOccurrence: z.coerce.date(),
  })),
  engineerHighlights: z.array(z.object({
    engineerId: z.string().uuid(),
    engineerName: z.string(),
    team: z.string(),
    highlight: z.string(),
    category: z.enum(['performance', 'quality', 'innovation', 'collaboration', 'customer-focus', 'leadership']),
    metrics: z.record(z.number()),
    period: z.object({
      start: z.coerce.date(),
      end: z.coerce.date(),
    }),
  })),
  recommendations: z.array(z.object({
    id: z.string().uuid(),
    title: z.string(),
    description: z.string(),
    priority: z.enum(['Low', 'Medium', 'High', 'Critical']),
    category: z.enum(['Process', 'Technology', 'People', 'Automation', 'Training', 'Governance']),
    effort: z.enum(['Low', 'Medium', 'High']),
    impact: z.enum(['Low', 'Medium', 'High', 'Critical']),
    owner: z.string(),
    targetDate: z.coerce.date(),
    status: z.enum(['proposed', 'approved', 'in-progress', 'completed', 'deferred']),
    relatedRisks: z.array(z.string()),
    relatedIssues: z.array(z.string()),
    kpis: z.array(z.string()),
  })),
  actionItems: z.array(z.object({
    id: z.string().uuid(),
    title: z.string(),
    description: z.string(),
    assignee: z.string(),
    assigneeEmail: z.string().email(),
    dueDate: z.coerce.date(),
    priority: z.enum(['Low', 'Medium', 'High', 'Critical']),
    status: z.enum(['pending', 'in-progress', 'completed', 'blocked', 'cancelled']),
    dependencies: z.array(z.string()),
    tags: z.array(z.string()),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
  })),
  appendix: z.object({
    methodology: z.string(),
    dataSources: z.array(z.string()),
    assumptions: z.array(z.string()),
    limitations: z.array(z.string()),
    glossary: z.record(z.string()),
    rawDataReferences: z.array(z.string()),
  }),
  metadata: z.record(z.unknown()),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});

export const aiAnalysisSchema = z.object({
  id: z.string().uuid(),
  ticketId: z.string().uuid(),
  executiveSummary: z.string(),
  condensedTechnicalSummary: z.string(),
  rootCause: z.string(),
  affectedApplication: z.string(),
  remediationSummary: z.string(),
  businessImpact: z.string(),
  recommendedPreventativeActions: z.array(z.string()),
  actionItems: z.array(z.object({
    id: z.string().uuid(),
    title: z.string(),
    description: z.string(),
    assignee: z.string(),
    assigneeEmail: z.string().email(),
    dueDate: z.coerce.date(),
    priority: z.enum(['Low', 'Medium', 'High', 'Critical']),
    status: z.enum(['pending', 'in-progress', 'completed', 'blocked', 'cancelled']),
    dependencies: z.array(z.string()),
    tags: z.array(z.string()),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
  })),
  confidenceScore: z.number().min(0).max(1),
  tags: z.array(z.string()),
  recurringIssueDetected: z.boolean(),
  recurringIssueId: z.string().uuid().optional(),
  similarTickets: z.array(z.string()),
  generatedBy: z.enum(['MockAI', 'OpenAI', 'Anthropic']),
  model: z.string(),
  generatedAt: z.coerce.date(),
  acknowledgedAt: z.coerce.date().optional(),
  acknowledgedBy: z.string().optional(),
});

export const executiveNarrativeSchema = z.object({
  id: z.string().uuid(),
  section: z.enum(['application-health', 'engineer-performance', 'recurring-issues', 'operational-risks', 'monthly-highlights', 'executive-summary', 'recommendations']),
  period: z.object({
    start: z.coerce.date(),
    end: z.coerce.date(),
  }),
  narrative: z.string(),
  keyMetrics: z.record(z.union([z.number(), z.string()])),
  references: z.array(z.string()),
  generatedBy: z.enum(['MockAI', 'OpenAI', 'Anthropic']),
  model: z.string(),
  generatedAt: z.coerce.date(),
  reviewedAt: z.coerce.date().optional(),
  reviewedBy: z.string().optional(),
});

export const applicationHealthScoreSchema = z.object({
  applicationId: z.string().uuid(),
  applicationName: z.string(),
  date: z.coerce.date(),
  healthScore: z.number().min(0).max(100),
  factors: z.object({
    ticketVolume: z.number(),
    avgSeverity: z.number(),
    slaViolations: z.number(),
    resolutionTime: z.number(),
    repeatIncidents: z.number(),
    reopenedTickets: z.number(),
    criticalIncidents: z.number(),
  }),
  weights: z.object({
    ticketVolume: z.number().min(0).max(1),
    avgSeverity: z.number().min(0).max(1),
    slaViolations: z.number().min(0).max(1),
    resolutionTime: z.number().min(0).max(1),
    repeatIncidents: z.number().min(0).max(1),
    reopenedTickets: z.number().min(0).max(1),
    criticalIncidents: z.number().min(0).max(1),
  }),
  riskLevel: z.enum(['Low', 'Medium', 'High', 'Critical']),
  trend: z.enum(['improving', 'stable', 'declining']),
  recommendedActions: z.array(z.string()),
  calculatedAt: z.coerce.date(),
});

export const trendHistorySchema = z.object({
  id: z.string().uuid(),
  metric: z.string(),
  dimension: z.string(),
  dimensionValue: z.string(),
  period: z.object({
    start: z.coerce.date(),
    end: z.coerce.date(),
  }),
  value: z.number(),
  previousValue: z.number().optional(),
  changePercent: z.number().optional(),
  trend: z.enum(['up', 'down', 'stable']),
  metadata: z.record(z.unknown()),
  createdAt: z.coerce.date(),
});

export type Engineer = z.infer<typeof engineerSchema>;
export type Application = z.infer<typeof applicationSchema>;
export type MonthlyReport = z.infer<typeof monthlyReportSchema>;
export type AIAnalysis = z.infer<typeof aiAnalysisSchema>;
export type ExecutiveNarrative = z.infer<typeof executiveNarrativeSchema>;
export type ApplicationHealthScore = z.infer<typeof applicationHealthScoreSchema>;
export type TrendHistory = z.infer<typeof trendHistorySchema>;