import React from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import { subMonths, startOfMonth, endOfMonth } from 'date-fns';
import {
  Box,
  Grid,
  Card,
  CardContent,
  Typography,
  Divider,
  Skeleton,
  Button,
  IconButton,
  Tooltip,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
} from '@mui/material';
import {
  Description as DescriptionIcon,
  Visibility as VisibilityIcon,
  Refresh as RefreshIcon,
  PictureAsPdf as PictureAsPdfIcon,
  TableChart as TableChartIcon,
  Add as AddIcon,
} from '@mui/icons-material';
import { reportApi, MonthlyReport } from '../../services/api';
import { useAuthStore } from '../../hooks/useAuthStore';
import { format } from 'date-fns';
import { safeParseJSON } from '../../utils/chipColors';
import PageHeader from '../../components/common/PageHeader';
import StatusPill from '../../components/ui/StatusPill';
import EmptyState from '../../components/ui/EmptyState';

const statusColors: Record<string, 'default' | 'primary' | 'secondary' | 'error' | 'warning' | 'info' | 'success'> = {
  draft: 'default',
  pending_review: 'warning',
  approved: 'info',
  published: 'success',
  archived: 'secondary',
};

type PeriodOption = 'last-month' | 'this-month' | 'last-quarter';

function getPeriodRange(period: PeriodOption): { start: Date; end: Date } {
  const now = new Date();
  switch (period) {
    case 'this-month':
      return { start: startOfMonth(now), end: endOfMonth(now) };
    case 'last-quarter':
      return { start: startOfMonth(subMonths(now, 3)), end: endOfMonth(subMonths(now, 1)) };
    case 'last-month':
    default:
      return { start: startOfMonth(subMonths(now, 1)), end: endOfMonth(subMonths(now, 1)) };
  }
}

interface Kpi {
  name: string;
  value: string | number;
  target?: string | number;
}

function reportKpis(report: MonthlyReport): Kpi[] {
  return safeParseJSON<Kpi[]>(report.kpis as unknown as string, []);
}

function downloadCsv(report: MonthlyReport) {
  const kpis = reportKpis(report);
  const escape = (v: unknown) => `"${String(v ?? '').replace(/"/g, '""')}"`;
  const lines = [
    ['Report', report.name].map(escape).join(','),
    ['Period', `${format(new Date(report.periodStart), 'MMM d, yyyy')} - ${format(new Date(report.periodEnd), 'MMM d, yyyy')}`].map(escape).join(','),
    ['Generated By', report.generatedBy].map(escape).join(','),
    ['Generated At', format(new Date(report.generatedAt), 'MMM d, yyyy h:mm a')].map(escape).join(','),
    '',
    ['Metric', 'Value', 'Target'].map(escape).join(','),
    ...kpis.map((k) => [k.name, k.value, k.target ?? ''].map(escape).join(',')),
    '',
    ['Executive Summary'].map(escape).join(','),
    [report.executiveSummary].map(escape).join(','),
  ];
  const blob = new Blob([lines.join('\r\n')], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${report.name.replace(/[^\w\- ]+/g, '').trim() || 'report'}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

// Rendered hidden on screen; @media print rules in main.tsx make it the only
// visible content, so the browser's Print → Save as PDF produces a clean
// standalone briefing document with no app chrome.
function PrintableBriefing({ report }: { report: MonthlyReport }) {
  const kpis = reportKpis(report);
  return (
    <div className="print-briefing">
      <div style={{ borderBottom: '3px solid #000', paddingBottom: 12, marginBottom: 16 }}>
        <div style={{ fontSize: 12, letterSpacing: 1, textTransform: 'uppercase', marginBottom: 4 }}>Executive Briefing Report</div>
        <div style={{ fontSize: 24, fontWeight: 700 }}>{report.name}</div>
        <div style={{ fontSize: 13, marginTop: 4 }}>
          Reporting period: {format(new Date(report.periodStart), 'MMMM d, yyyy')} – {format(new Date(report.periodEnd), 'MMMM d, yyyy')}
        </div>
        <div style={{ fontSize: 12, color: '#333' }}>
          Generated {format(new Date(report.generatedAt), 'MMMM d, yyyy h:mm a')} by {report.generatedBy} · Status: {report.status}
        </div>
      </div>

      <div style={{ fontSize: 14, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 8 }}>Key Metrics</div>
      <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: 20, fontSize: 13 }}>
        <thead>
          <tr>
            <th style={{ textAlign: 'left', borderBottom: '2px solid #000', padding: '6px 8px' }}>Metric</th>
            <th style={{ textAlign: 'right', borderBottom: '2px solid #000', padding: '6px 8px' }}>Value</th>
            <th style={{ textAlign: 'right', borderBottom: '2px solid #000', padding: '6px 8px' }}>Target</th>
          </tr>
        </thead>
        <tbody>
          {kpis.map((k, i) => (
            <tr key={i}>
              <td style={{ borderBottom: '1px solid #ccc', padding: '6px 8px' }}>{k.name}</td>
              <td style={{ borderBottom: '1px solid #ccc', padding: '6px 8px', textAlign: 'right', fontWeight: 600 }}>{k.value}</td>
              <td style={{ borderBottom: '1px solid #ccc', padding: '6px 8px', textAlign: 'right' }}>{k.target ?? '—'}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div style={{ fontSize: 14, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 8 }}>Executive Summary</div>
      <div style={{ fontSize: 13, lineHeight: 1.7, whiteSpace: 'pre-wrap' }}>{report.executiveSummary}</div>

      <div style={{ marginTop: 32, paddingTop: 8, borderTop: '1px solid #ccc', fontSize: 11, color: '#555' }}>
        Produced by the Jira Executive Reporting Platform · Printed {format(new Date(), 'MMMM d, yyyy h:mm a')}
      </div>
    </div>
  );
}

export default function ReportsPage() {
  const queryClient = useQueryClient();
  const { user } = useAuthStore();

  const { data: reports, isLoading, refetch, isRefetching } = useQuery({
    queryKey: ['monthly-reports'],
    queryFn: () => reportApi.getMonthlyReports().then((r) => r.data),
  });

  const [selectedReport, setSelectedReport] = React.useState<MonthlyReport | null>(null);
  const [dialogOpen, setDialogOpen] = React.useState(false);
  const [newReportTitle, setNewReportTitle] = React.useState('');
  const [period, setPeriod] = React.useState<PeriodOption>('last-month');
  const [template, setTemplate] = React.useState('standard');
  const [printReport, setPrintReport] = React.useState<MonthlyReport | null>(null);

  const generateMutation = useMutation({
    mutationFn: () => {
      const { start, end } = getPeriodRange(period);
      return reportApi.generate({
        name: newReportTitle.trim() || `Executive Report - ${format(start, 'MMMM yyyy')}`,
        periodStart: start.toISOString(),
        periodEnd: end.toISOString(),
        generatedBy: user?.name,
      }).then((r) => r.data);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['monthly-reports'] });
      toast.success('Report generated');
      setDialogOpen(false);
      setNewReportTitle('');
    },
    onError: () => {
      toast.error('Failed to generate report');
    },
  });

  const openGenerateDialog = () => {
    setSelectedReport(null);
    setNewReportTitle('');
    setPeriod('last-month');
    setTemplate('standard');
    setDialogOpen(true);
  };

  // Mount the printable document, let React commit it, then open the print dialog.
  const handlePrint = (report: MonthlyReport) => {
    setPrintReport(report);
    setTimeout(() => {
      window.print();
      setPrintReport(null);
    }, 100);
  };

  if (isLoading) {
    return (
      <Grid container spacing={3}>
        {[...Array(4)].map((_, i) => (
          <Grid item xs={12} sm={6} md={3} key={i}>
            <Skeleton variant="rectangular" height={180} sx={{ borderRadius: 2 }} />
          </Grid>
        ))}
      </Grid>
    );
  }

  return (
    <Box sx={{ flexGrow: 1 }}>
      <PageHeader
        eyebrow="Briefing"
        title="Executive Reports"
        subtitle="Period reports generated from live ticket data, ready to print or distribute"
        actions={
          <>
            <Button variant="outlined" size="small" startIcon={<RefreshIcon sx={{ fontSize: 16 }} />} onClick={() => refetch()} disabled={isRefetching}>
              Refresh
            </Button>
            <Button variant="contained" size="small" startIcon={<AddIcon sx={{ fontSize: 16 }} />} onClick={openGenerateDialog}>
              Generate report
            </Button>
          </>
        }
      />

      <Grid container spacing={2}>
        {reports?.map((report) => {
          const kpis = reportKpis(report);
          return (
            <Grid item xs={12} md={6} xl={4} key={report.id}>
              <Card
                sx={{
                  height: '100%', display: 'flex', flexDirection: 'column',
                  '&:hover': { borderColor: 'surface.borderStrong', boxShadow: 1 },
                }}
              >
                <Box sx={{ p: 2.25, pb: 1.75, display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 1.5 }}>
                  <Box sx={{ minWidth: 0 }}>
                    <Typography variant="h6" sx={{ mb: 0.375 }}>{report.name}</Typography>
                    <Typography variant="caption" color="text.secondary" className="tabular-nums">
                      {format(new Date(report.periodStart), 'MMM d')} – {format(new Date(report.periodEnd), 'MMM d, yyyy')}
                    </Typography>
                  </Box>
                  <StatusPill
                    label={report.status.replace('_', ' ')}
                    color={statusColors[report.status] || 'default'}
                  />
                </Box>

                {kpis.length > 0 && (
                  <Box sx={{ px: 2.25, pb: 1.75, display: 'flex', gap: 2, flexWrap: 'wrap' }}>
                    {kpis.slice(0, 3).map((k, i) => (
                      <Box key={i} sx={{ minWidth: 62 }}>
                        <Typography className="tabular-nums" sx={{ fontSize: '1.0625rem', fontWeight: 680, lineHeight: 1.2 }}>
                          {k.value}
                        </Typography>
                        <Typography sx={{ fontSize: '0.6875rem', color: 'text.secondary' }} noWrap>{k.name}</Typography>
                      </Box>
                    ))}
                  </Box>
                )}

                <Divider />
                <Box sx={{ p: 2.25, flexGrow: 1 }}>
                  <Typography
                    variant="body2"
                    color="text.secondary"
                    sx={{ lineHeight: 1.65, display: '-webkit-box', WebkitLineClamp: 3, WebkitBoxOrient: 'vertical', overflow: 'hidden' }}
                  >
                    {report.executiveSummary}
                  </Typography>
                </Box>

                <Box sx={{ px: 2.25, py: 1.5, borderTop: '1px solid', borderColor: 'divider', display: 'flex', alignItems: 'center', gap: 0.5 }}>
                  <Button size="small" startIcon={<VisibilityIcon sx={{ fontSize: 15 }} />} onClick={() => setSelectedReport(report)}>
                    View
                  </Button>
                  <Box sx={{ flexGrow: 1 }} />
                  <Tooltip title="Print / Save as PDF">
                    <IconButton size="small" onClick={() => handlePrint(report)}><PictureAsPdfIcon sx={{ fontSize: 17 }} /></IconButton>
                  </Tooltip>
                  <Tooltip title="Download CSV">
                    <IconButton size="small" onClick={() => downloadCsv(report)}><TableChartIcon sx={{ fontSize: 17 }} /></IconButton>
                  </Tooltip>
                </Box>
              </Card>
            </Grid>
          );
        })}
        {(!reports || reports.length === 0) && (
          <Grid item xs={12}>
            <Card>
              <EmptyState
                icon={<DescriptionIcon />}
                title="No reports yet"
                description="Generate a report to capture this period's KPIs and executive summary as a shareable briefing document."
                action={
                  <Button variant="contained" size="small" startIcon={<AddIcon sx={{ fontSize: 16 }} />} onClick={openGenerateDialog}>
                    Generate report
                  </Button>
                }
              />
            </Card>
          </Grid>
        )}
      </Grid>

      {/* Report Detail / Generate Dialog */}
      <Dialog open={dialogOpen} onClose={() => { setDialogOpen(false); setSelectedReport(null); }} maxWidth="lg" fullWidth>
        <DialogTitle>{selectedReport ? 'Report Details' : 'Generate New Report'}</DialogTitle>
        <DialogContent dividers>
          {selectedReport ? (
            <Box sx={{ p: 2 }}>
              <Typography variant="h6" sx={{ fontWeight: 600, mb: 1 }}>{selectedReport.name}</Typography>
              <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
                Period: {format(new Date(selectedReport.periodStart), 'MMM d, yyyy')} – {format(new Date(selectedReport.periodEnd), 'MMM d, yyyy')}
              </Typography>
              <Typography variant="body1" sx={{ lineHeight: 1.7, mb: 3, whiteSpace: 'pre-wrap' }}>
                {selectedReport.executiveSummary}
              </Typography>
              <Divider sx={{ mb: 2 }} />
              <Typography variant="subtitle1" sx={{ fontWeight: 600, mb: 1 }}>Key Metrics</Typography>
              <Grid container spacing={2}>
                {safeParseJSON<Kpi[]>(selectedReport.kpis as unknown as string, []).map((kpi, i) => (
                  <Grid item xs={6} sm={3} key={i}>
                    <Card variant="outlined">
                      <CardContent>
                        <Typography variant="caption" color="text.secondary">{kpi.name}</Typography>
                        <Typography variant="h6" sx={{ fontWeight: 700 }}>{kpi.value}</Typography>
                        {kpi.target !== undefined && (
                          <Typography variant="caption" color="text.secondary">Target: {kpi.target}</Typography>
                        )}
                      </CardContent>
                    </Card>
                  </Grid>
                ))}
              </Grid>
            </Box>
          ) : (
            <Box sx={{ p: 2 }}>
              <TextField
                fullWidth
                label="Report Title"
                value={newReportTitle}
                onChange={(e) => setNewReportTitle(e.target.value)}
                placeholder="e.g., Executive Service Desk Report - January 2026"
                sx={{ mb: 2 }}
              />
              <FormControl fullWidth sx={{ mb: 2 }}>
                <InputLabel>Period</InputLabel>
                <Select label="Period" value={period} onChange={(e) => setPeriod(e.target.value as PeriodOption)}>
                  <MenuItem value="last-month">Last Month</MenuItem>
                  <MenuItem value="this-month">This Month</MenuItem>
                  <MenuItem value="last-quarter">Last Quarter</MenuItem>
                </Select>
              </FormControl>
              <FormControl fullWidth sx={{ mb: 2 }}>
                <InputLabel>Template</InputLabel>
                <Select label="Template" value={template} onChange={(e) => setTemplate(e.target.value)}>
                  <MenuItem value="standard">Standard Executive Report</MenuItem>
                  <MenuItem value="detailed">Detailed Operational Report</MenuItem>
                  <MenuItem value="executive-summary">Executive Summary Only</MenuItem>
                </Select>
              </FormControl>
              <Typography variant="caption" color="text.secondary" display="block" sx={{ mb: 2 }}>
                The report will be generated from tickets created during the selected period, with KPIs and an executive summary computed from live data.
              </Typography>
            </Box>
          )}
        </DialogContent>
        <DialogActions>
          <Button onClick={() => { setDialogOpen(false); setSelectedReport(null); }}>Cancel</Button>
          {selectedReport ? (
            <>
              <Button variant="outlined" startIcon={<PictureAsPdfIcon />} onClick={() => handlePrint(selectedReport)}>Print / Save as PDF</Button>
              <Button variant="outlined" startIcon={<TableChartIcon />} onClick={() => downloadCsv(selectedReport)}>Download CSV</Button>
            </>
          ) : (
            <Button
              variant="contained"
              startIcon={<AddIcon />}
              onClick={() => generateMutation.mutate()}
              disabled={generateMutation.isPending}
            >
              {generateMutation.isPending ? 'Generating…' : 'Generate Report'}
            </Button>
          )}
        </DialogActions>
      </Dialog>

      {printReport && <PrintableBriefing report={printReport} />}
    </Box>
  );
}
